name: Push to Azure Container Registry and Deploy to AKS
on:
  push:
    branches:
      - main

jobs:
  push-and-deploy-to-aks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
 

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io
          username: ${{ secrets.AZ_SP_CLIENT_ID }}
          password: ${{ secrets.AZ_SP_CLIENT_SECRET }}

 
      - name: Build and push Docker image to Azure Container Registry
        env:
          IMAGE_NAME: mydemoapp
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker buildx build --push --tag ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io/$IMAGE_NAME:$IMAGE_TAG .


      - name: Deploy to AKS
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: gitakstest
          cluster-name: gitakstestcluster

 
      - name: Apply Kubernetes deployment
        uses: azure/k8s-deploy@v1
        with:
          manifests: |
            kubernetes/pyflask.yaml
          images: |
            ${{ secrets.ACR_REGISTRY_NAME }}.azurecr.io/mydemoapp:${{ github.sha }}
